name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login ghcr.io -u thierrycz --password ${{ secrets.PAT }}
        docker build . --file Dockerfile -t ghcr.io/thierrycz/nginx-test:0.1
        docker push ghcr.io/thierrycz/nginx-test:0.1
      
