name: Docker Image CI iceberg

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: |
        echo $PATH
        pwd
        set -vx
        curl -s -O https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc
        ./mc alias set b2 https://s3.eu-central-003.backblazeb2.com ${{ secrets.ACCESSKEY }} ${{ secrets.SECRETKEY }}
        ./mc ls --recursive b2
        mkdir my-plugins
        ./mc cp b2/monbucket666/kafka-serde-tools.tgz /home/runner/my-plugins/
        cd my-plugins
        tar zxf kafka-serde-tools.tgz
        ls -l
        #wget -q https://github.com/databricks/iceberg-kafka-connect/releases/download/v0.6.19/iceberg-kafka-connect-runtime-0.6.19.zip  
        #wget -q https://github.com/databricks/iceberg-kafka-connect/releases/download/v0.6.19/iceberg-kafka-connect-runtime-hive-0.6.19.zip 
        cd ..
        echo ${{ secrets.PAT }} | docker login ghcr.io -u thierrycz --password-stdin
        #docker build . --file Dockerfile-connect-iceberg -t ghcr.io/thierrycz/kafka-connect-iceberg-avro:0.1
        #docker push ghcr.io/thierrycz/kafka-connect-iceberg:0.1
      
